// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh3XZsFlTd6dq7B_VK0zbuAbiTyKwBVP8',
    appId: '1:117114619025:web:f78e9a4d14c8c9b5822b30',
    messagingSenderId: '117114619025',
    projectId: 'apexo-87173',
    authDomain: 'apexo-87173.firebaseapp.com',
    storageBucket: 'apexo-87173.firebasestorage.app',
    measurementId: 'G-RGF6ZWKBL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsxadgBBzfk-q7zLTueRTRfbKoZvASqH4',
    appId: '1:117114619025:android:32f77a2047ec91ba822b30',
    messagingSenderId: '117114619025',
    projectId: 'apexo-87173',
    storageBucket: 'apexo-87173.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV8JFyzqaYXVTJnDqsGlNjaoAXaxhO5fA',
    appId: '1:117114619025:ios:c3bc60481255d184822b30',
    messagingSenderId: '117114619025',
    projectId: 'apexo-87173',
    storageBucket: 'apexo-87173.firebasestorage.app',
    iosBundleId: 'com.example.alexo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV8JFyzqaYXVTJnDqsGlNjaoAXaxhO5fA',
    appId: '1:117114619025:ios:c3bc60481255d184822b30',
    messagingSenderId: '117114619025',
    projectId: 'apexo-87173',
    storageBucket: 'apexo-87173.firebasestorage.app',
    iosBundleId: 'com.example.alexo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh3XZsFlTd6dq7B_VK0zbuAbiTyKwBVP8',
    appId: '1:117114619025:web:66c36323cfafa9ce822b30',
    messagingSenderId: '117114619025',
    projectId: 'apexo-87173',
    authDomain: 'apexo-87173.firebaseapp.com',
    storageBucket: 'apexo-87173.firebasestorage.app',
    measurementId: 'G-K5CMMWSZWY',
  );
}
